### ISSUE TITLE
Install/launch - returned non-zero exit status 53

### ISSUE THREAD

**Issue by BakiDance** [Kuuchuu/BG3ModManager-LinuxLauncher#1]
I've run the script, and it seems to have created the necessary Wine prefix, however I'm still unable to launch the mod manager on Fedora.

```
[baki@baki-pc BG3ModManager_Latest]$ python linux.py --setup
Please 'pip install vdf pefile' for adding to Steam
Checking if WINEPREFIX exists...
Installing dotnet472 if necessary...
Running wine
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212 - sha256sum: e882a17654b1138109ed0211ae9726839683c91cf13dff24a012f6712375ebf2 with wine-8.14 (Staging) and WINEARCH=win64
Executing w_do_call dotnet472
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
dotnet472 already installed, skipping
Installing d3dcompiler_47 if necessary...
Running wine
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212 - sha256sum: e882a17654b1138109ed0211ae9726839683c91cf13dff24a012f6712375ebf2 with wine-8.14 (Staging) and WINEARCH=win64
Executing w_do_call d3dcompiler_47
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
d3dcompiler_47 already installed, skipping
Updating settings.json...
Checking if settings.json exists...
Updating settings.json...
```
```
[baki@baki-pc BG3ModManager_Latest]$ python linux.py
Please 'pip install vdf pefile' for adding to Steam
Checking if WINEPREFIX exists...
Running wine
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.14 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0118:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"BG3ModManager.exe" cannot be loaded
0118:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\baki\\Downloads\\BG3ModManager_Latest\\BG3ModManager.exe" failed, status c0000135
Traceback (most recent call last):
  File "/home/baki/Downloads/BG3ModManager_Latest/linux.py", line 178, in <module>
    main()
  File "/home/baki/Downloads/BG3ModManager_Latest/linux.py", line 174, in main
    run_command(f"WINEPREFIX={prefix_location} wine BG3ModManager.exe")
  File "/home/baki/Downloads/BG3ModManager_Latest/linux.py", line 21, in run_command
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'WINEPREFIX=/home/baki/.local/share/wineprefixes/BG3MM/ wine BG3ModManager.exe' returned non-zero exit status 53.
```

**Comment by Kuuchuu** [comment]
I'm assuming in the log you provided you left out the dotnet472 & d3dcompiler_47 install log, right? Just want to make sure. After grabbing the latest version of the script, go ahead and run it again with the clean flag `./linux.py --setup --clean`

**Comment by BakiDance** [comment]
I was able to get it to work without the script, but I honestly don't know what I did differently this time to get it to work. This was my 4th attempt at making a prefix manually, and for some god-forsaken reason it worked this time, haha. If there's a way I can check what's different in my current (working) prefix, I'll happily provide it.
